ci: optimized build leveraging macos runner for publishing

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -24,17 +24,12 @@ jobs:
         run: |
           echo "run-with-secrets=${{ steps.detect-secrets.outputs.has-secrets == 'true' && !github.event.repository.fork }}" >> $GITHUB_OUTPUT
 
-  staging-repo:
+  precompute-next-version:
     runs-on: ubuntu-24.04
-    needs:
-      - check-secrets
-    if: ${{ needs.check-secrets.outputs.run-with-secrets == 'true' }}
     outputs:
-      maven-central-repo-id: ${{ steps.staging-repo.outputs.MavenCentral }}
       next-version: ${{ steps.compute-next-version.outputs.next-version }}
-      will-release: ${{ steps.compute-next-version.outputs.will-release }}
     steps:
-      - name: Checkout the repo
+      - name: Checkout
         uses: actions/checkout@v4.2.2
         with:
           fetch-depth: 0
@@ -43,72 +38,54 @@ jobs:
         uses: nicolasfara/precompute-semantic-release-version-action@2.0.2
         with:
           github-token: ${{ github.token }}
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
-        with:
-          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          should-run-codecov: false
-          should-deploy: true
-          build-command: true
-          check-command: true
-          deploy-command: |
-            if [[ "${{ steps.compute-next-version.outputs.will-release }}" == "true" ]]; then
-              ./gradlew -PforceVersion="${{ steps.compute-next-version.outputs.next-version }}" createStagingRepositoryOnMavenCentral --parallel
-            else
-              ./gradlew createStagingRepositoryOnMavenCentral --parallel
-            fi
-      - name: Save staging repository ID
-        id: staging-repo
-        run: |
-          [[ -f build/staging-repo-ids.properties ]] || (
-            echo "Staging repositories ID file not found" &&
-            exit 1
-          )
-          REPO_IDS=$(cat build/staging-repo-ids.properties)
-          echo "Staging repositories IDs:\n$REPO_IDS"
-          echo $REPO_IDS >> $GITHUB_OUTPUT
 
   build:
     needs:
       - check-secrets
-      - staging-repo
-    if: ${{ always() && !contains(needs.staging-repo.result, 'failure') }}
+      - precompute-next-version
+    if: always() && !contains(needs.precompute-next-version.result, 'failure')
     strategy:
       fail-fast: false
       matrix:
         os: [ windows-2022, macos-14, ubuntu-24.04 ]
     runs-on: ${{ matrix.os }}
+    outputs:
+      staging-repo-id: ${{ steps.staging-repo.outputs.MavenCentral || '' }}
     steps:
-      - name: Checkout the repo
+      - name: Checkout
         uses: actions/checkout@v4.2.2
         with:
           fetch-depth: 0
       - uses: DanySK/build-check-deploy-gradle-action@3.5.25
+        id: staging-repo
         with:
-          # Dry-deployment
-          check-command: |
-            ./gradlew check koverXmlReport :compiler-plugin:check :gradle-plugin:check --parallel
+          should-deploy: ${{ runner.os == 'macOS' && needs.check-secrets.outputs.run-with-secrets == 'true' }} # Deploy from macOS since it supports all the platforms
           deploy-command: |
-            # Stop the Gradle Daemon on windows to try to prevent
-            # "The process cannot access the file because it is being used by another process"
-            if ${{ runner.os == 'Windows' }}; then
-              ./gradlew --stop
-            fi
-            NEXT_VERSION="${{ needs.staging-repo.outputs.next-version }}"
+            NEXT_VERSION="${{ needs.precompute-next-version.outputs.next-version }}"
             OVERRIDE_VERSION=$([[ "$NEXT_VERSION" != "" ]] && echo "-PforceVersion=$(echo $NEXT_VERSION)" || echo "")
-            ./gradlew $OVERRIDE_VERSION -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} uploadAll :compiler-plugin:uploadKotlinOSSRHToMavenCentralNexus :gradle-plugin:uploadKotlinOSSRHToMavenCentralNexus --parallel
+            ./gradlew createStagingRepositoryOnMavenCentral --parallel
+
+            [[ -f build/staging-repo-ids.properties ]] || (
+              echo "Staging repositories ID file not found" &&
+              exit 1
+            )
+            REPO_IDS=$(cat build/staging-repo-ids.properties)
+            echo -e "Staging repositories IDs:\n$REPO_IDS"            
+            MAVEN_CENTRAL_STAGING_ID=${REPO_IDS#MavenCentral=}
+            echo "MavenCentral=$MAVEN_CENTRAL_STAGING_ID" >> $GITHUB_OUTPUT
+            ./gradlew $OVERRIDE_VERSION -PstagingRepositoryId=$MAVEN_CENTRAL_STAGING_ID uploadAll close --parallel
           should-run-codecov: ${{ runner.os == 'Linux' }}
-          codecov-directory: build/reports/kover
           codecov-token: ${{ secrets.CODECOV_TOKEN }}
-          should-deploy: ${{ needs.check-secrets.outputs.run-with-secrets == 'true' }}
           maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
           maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          signing-key: ${{ secrets.GPG_PRIVATEKEY }}
-          signing-password: ${{ secrets.GPG_PASSPHRASE }}
-      - uses: github/codeql-action/upload-sarif@v3
-        if: ${{ runner.os == 'Linux' }}
+          signing-key: ${{ secrets.SIGNING_KEY }}
+          signing-password: ${{ secrets.SIGNING_PASSWORD }}
+      - name: Upload staging repository file
+        uses: actions/upload-artifact@v4
+        if: ${{ runner.os == 'macOS' && needs.check-secrets.outputs.run-with-secrets == 'true' }}
         with:
-          sarif_file: build/reports
+          name: staging-repo-ids
+          path: build/staging-repo-ids.properties
 
   build-website:
     runs-on: ubuntu-24.04
@@ -135,36 +112,15 @@ jobs:
           name: website-${{ github.sha }}
           path: website.tar
 
-  close-staging-repos:
-    needs:
-      - staging-repo
-      - build
-    runs-on: ubuntu-24.04
-    if: ${{ needs.check-secrets.outputs.run-with-secrets == 'true' }}
-    steps:
-      - name: Checkout the repo
-        uses: actions/checkout@v4.2.2
-      - uses: DanySK/build-check-deploy-gradle-action@3.5.25
-        with:
-          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          should-run-codecov: false
-          should-deploy: true
-          build-command: true
-          check-command: true
-          deploy-command: |
-            ./gradlew -PstagingRepositoryId=${{ needs.staging-repo.outputs.maven-central-repo-id }} close --parallel
-
   release:
     concurrency:
       group: release-${{ github.workflow }}-${{ github.event.number || github.ref }}
       cancel-in-progress: false
     needs:
       - check-secrets
-      - staging-repo
+      - precompute-next-version
       - build-website
       - build
-      - close-staging-repos
     runs-on: ubuntu-24.04
     # Prevent the release job if the run is on a PR or a fork
     if: ${{ needs.check-secrets.outputs.run-with-secrets == 'true' }}
@@ -198,7 +154,7 @@ jobs:
           node-version-file: package.json
       - uses: DanySK/build-check-deploy-gradle-action@3.5.25
         env:
-          STAGING_REPO_ID: ${{ needs.staging-repo.outputs.maven-central-repo-id }}
+          STAGING_REPO_ID: ${{ needs.build.outputs.staging-repo-id }}
           ORG_GRADLE_PROJECT_releaseStage: true
         with:
           retries-on-failure: 1 # Fail fast during release
@@ -221,8 +177,6 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - check-secrets
-      - staging-repo
-      - close-staging-repos
       - build-website
       - release
       - build
@@ -239,6 +193,7 @@ jobs:
 
   drop-staging-repos:
     needs:
+      - build
       - success
     runs-on: ubuntu-24.04
     if: always()
